# Generated by Django 5.2.6 on 2025-12-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem_perfil',
            field=models.ImageField(blank=True, upload_to='perfil/'),
        ),
    ]
