# Generated by Django 5.2.6 on 2025-12-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('funcionario', 'Funcionário')], default='empresa', max_length=20),
        ),
    ]
