"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#secret key modificada para acompanhar o tutorial do deploy

SECRET_KEY = os.environ.get('SECRET_KEY', default='local') # Essa SECRET_KEY é vinculada a que está no ".env"
# a secrete_key acima serve para o dar deploy do servidor com docker (descomente, e comente o outro para funcionar)
# a secret_key abaixo server para rodar o projeto com django pelo terminal (runserver)
# DEFAULT='LOCAL' RODA O PROJETO LOCALMENTE

# SECRET_KEY = 'minha_grande_senha'
# qualquer coisa entre as aspas vai fazer o site funcionar

# SECURITY WARNING: don't run with debug turned on in production!
#dados modificados para acompanhar o tutorial do deploy

DEBUG = os.environ.get('DEBUG', True) == "true"
# o debug acima serve para trabalhar com deploy do projeto com docker.
#  Atualizado: o de cima serve para ambos (localmente e numa máquina virtual). Peguei essa dica de um projeto no git do professor Diego
# o debug abaixo serve para rodar o projeto com django pelo terminal (runserver)

# DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']  
# essa configuração de allowed hosts serve para os dois, tanto com docker quanto com runserver
# chatgpt diz que não é seguro, mas não importa já que é a configuração do tutorial do professor


# Application definition

INSTALLED_APPS = [
    "usuarios",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "crispy_forms",
    "crispy_bootstrap5",
    "control",
    "cadastros",
    "dashboard",
    "vendas",
    "estoque",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': os.environ.get('POSTGRES_DB'),
#        'USER': os.environ.get('POSTGRES_USER'),
#        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
#        'HOST': os.environ.get('DB_HOST'),
#        'PORT': os.environ.get('DB_PORT'),
#    }
#}
# O database acima serve para rodar o projeto com docker em um servidor
# o database abaixo serve para rodar o projeto com django (runserver)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Recife'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'
 # Adiicionar esse STATIC_ROOT é NECESSARIO para rodar o projeto com docker, e não interfere no django normal (runserver)
MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / "media/"


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'usuarios.Usuario'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

LOGIN_URL = "login"
LOGOUT_REDIRECT_URL = "index"
LOGIN_REDIRECT_URL = "dashboard:index"

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"