# Generated by Django 5.2.6 on 2025-12-16 00:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('clientes', 'Clientes'), ('produtos', 'Produtos'), ('vendedores', 'Vendedores'), ('funcionarios', 'Funcionarios'), ('categorias', 'Categorias'), ('fornecedores', 'Fornecedores')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=20)),
                ('quantidade', models.IntegerField()),
                ('dataehora', models.DateTimeField(default=django.utils.timezone.now)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco_compra', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('aberto', 'Em aberto'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos_Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('pagamento', models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('boleto', 'Boleto')], max_length=20)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('aberto', 'Em aberto'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valor_frete', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('frete', models.CharField(blank=True, choices=[('cif', 'CIF - Frete Incluso'), ('fob', 'FOB - Frete por Conta do Cliente'), ('retirar', 'Retirar no Local')], max_length=30)),
                ('cidade', models.CharField(blank=True, max_length=50)),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('logradouro', models.CharField(blank=True, max_length=100)),
                ('numero', models.CharField(blank=True, max_length=7)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagem', models.ImageField(blank=True, upload_to='imagens/')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(default='', max_length=254)),
                ('telefone', models.CharField(default='', max_length=11)),
            ],
            options={
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(default='', max_length=254)),
                ('telefone', models.CharField(default='', max_length=11)),
                ('cidade', models.CharField(blank=True, max_length=50)),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('logradouro', models.CharField(blank=True, max_length=100)),
                ('numero', models.CharField(blank=True, max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control.estado')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.estado'),
        ),
        migrations.CreateModel(
            name='Estoque_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.deposito')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('email', models.EmailField(default='', max_length=254)),
                ('telefone', models.CharField(default='', max_length=11)),
                ('cidade', models.CharField(default='', max_length=50)),
                ('bairro', models.CharField(default='', max_length=50)),
                ('logradouro', models.CharField(default='', max_length=100)),
                ('numero', models.CharField(default='', max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(default='', max_length=8)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.estado')),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
    ]
