# Generated by Django 5.2.6 on 2025-10-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_produto',
            name='descricao',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
