# Generated by Django 5.2.6 on 2025-12-16 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_funcionario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicoacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.deposito'),
        ),
        migrations.AddField(
            model_name='pedidos_compra',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.fornecedor'),
        ),
        migrations.AddField(
            model_name='pedidos_venda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.cliente'),
        ),
        migrations.AddField(
            model_name='pedidos_venda',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control.estado'),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.categoria_produto'),
        ),
        migrations.AddField(
            model_name='pedidos_venda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.produto'),
        ),
        migrations.AddField(
            model_name='pedidos_compra',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.produto'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.produto'),
        ),
        migrations.AddField(
            model_name='estoque_produto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.produto'),
        ),
        migrations.AddField(
            model_name='pedidos_venda',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.vendedor'),
        ),
    ]
