# Generated by Django 5.2.6 on 2025-10-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_categoria_produto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
