# Generated by Django 5.2.6 on 2025-10-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_remove_usuario_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
