# Generated by Django 5.2.6 on 2025-11-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name_plural': 'Vendedores'},
        ),
    ]
