# Generated by Django 5.2.6 on 2025-11-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos_venda',
            name='data',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
