# Generated by Django 5.2.6 on 2025-11-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_pedidos_venda_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_venda',
            name='data',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
