# Generated by Django 5.2.6 on 2025-11-28 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_alter_pedidos_venda_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_venda',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
