# Generated by Django 5.2.6 on 2025-11-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_alter_pedidos_venda_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
