# Generated by Django 5.2.6 on 2025-11-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos_venda',
            name='status',
            field=models.CharField(choices=[('aberto', 'Em aberto'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=20),
        ),
    ]
