# Generated by Django 5.2.6 on 2025-11-29 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_pedidos_venda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_venda',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
