# Generated by Django 5.2.6 on 2025-12-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_alter_pedidos_venda_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='preco_compra',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='pedidos_compra',
            name='status',
            field=models.CharField(choices=[('aberto', 'Em aberto'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=20),
        ),
    ]
